// Human-verified descriptions of the curated Unsplash practice photos, written
// by looking at each actual image at development time. They let text-only
// providers (DeepSeek, installed CLI) grade picture tasks against what is REALLY
// in the photo instead of guessing from the title — see gradeMaybeWithImage in
// ai.ts. Keyed by the Unsplash photo id so any size/crop variant of the same
// photo matches. Note: some descriptions intentionally differ from the practice
// item's title (e.g. the "loading boxes" photo actually shows a backpack) —
// the description reflects the real image and is the ground truth for grading.
const UNSPLASH_PHOTO_DESCRIPTIONS: Record<string, string> = {
  // People having a meeting in an office
  '1690378820474-b468b8ee64d3':
    'A bright, modern open-plan office with floor-to-ceiling glass partition walls, a grey concrete pillar on the left, and large windows at the back letting in daylight. Three young colleagues gather around a white desk with two silver Apple MacBook laptops. On the left, a man with light-brown hair combed back and black rectangular glasses, wearing a pale-blue short-sleeved shirt, sits typing on his laptop. On the right, a smiling young woman with long, straight dark-brown hair, wearing a plain white T-shirt, sits on an olive-green chair in front of the second laptop. Between them, a man with short brown hair and light stubble, wearing an unbuttoned light-blue shirt over a white T-shirt and blue jeans, stands and leans forward to look at the woman\'s screen. In the blurred background, a dark-haired woman in a light-blue shirt gestures at a glass wall with white papers pinned to it, and a man in a royal-blue polo shirt and dark trousers stands near a glass-walled meeting room. Empty white desks, black chairs, and a vase with orange flowers fill the rest of the office; a small white gadget (earbuds/phone) lies on the desk in the near foreground.',

  // A busy street market with vendors
  '1749197894518-623876b9181f':
    'A crowded outdoor Asian street market, dominated by red colors. In the foreground, an elderly woman with short grey hair, wearing a blue-and-white plaid shirt with a dark bag strap across her chest, sits behind her stall and stretches her right arm across a tray of long, pale cream sausage-shaped foods (rice cakes or rolls); tall curved bamboo handles or hooks arch above the tray. Two large red parasols with white "Coca-Cola" logos shade the stalls, and a red Coca-Cola banner is wrapped around a pole in the middle. On the left, a table draped in a red cloth holds stacks of round, golden-brown pastries (mooncake-style) in clear plastic wrap, next to white plastic bags and brown cardboard boxes; more cardboard boxes with blue printing sit on the right. In the blurred background, a busy crowd of shoppers fills the street: a woman in a purple T-shirt with a white shoulder bag, a man in a light shirt wearing a white face mask, a person in a red top by the next stall, and many others. Overhead hang colorful yellow-and-red signs with Chinese characters, and warm golden lights glow at a stall in the middle distance.',

  // Family cooking together in a kitchen
  '1556910103-1c02745aae4d':
    'A bright white kitchen with white subway-tile walls, white cabinets, a built-in stainless-steel microwave and oven on the left, and dark wooden open shelves on the right holding white bowls, plates, glasses, a turquoise pot and trailing green plants. Three people are cooking at a dark rustic wooden island. In the center, a smiling young man with short brown hair, round tortoiseshell glasses and light stubble, wearing an olive-green T-shirt and a dark charcoal apron, holds a small glass jar in one hand and spoons a dark-red ingredient with a small brass spoon toward a turquoise enamel cast-iron pot with a white interior. To his right, a smiling woman with long, wavy dark hair, wearing a chunky cream knitted sweater, rests her hand near a glass jar of amber honey on the counter. In the left background, a third person with dark hair in a low bun, wearing a navy top and a dark apron, stands at the black stove with their back to the camera. On the island: a tall bottle of olive oil with a pour spout, a dark stone mortar and pestle, a turquoise lidded canister, a turquoise pot lid on a wooden board, small blue glass bottles, a grey-striped tea towel, and on the left a large turquoise dish filled with a colorful salad of purple cabbage and greens.',

  // Workers loading boxes onto a truck (actual photo shows a bag, not boxes)
  '1774977867718-e926bedc8740':
    'An outdoor scene under large leafy trees, with strong sunlight breaking through the canopy and deep shadows. An orange flatbed truck with dark metal railing frames around its bed is parked; its orange-red tailgate carries big embossed letters spelling "EICHER", with smaller yellow letters "SOUND" and "HORN" painted below. On the truck bed, a young man with dark skin, wearing a navy-and-white horizontally striped shirt, blue jeans and a black cap turned backwards, bends down holding a black backpack in his left hand, lowering or lifting it. Standing on the ground behind the truck is an older man with grey balding hair, wearing a white sleeveless vest and dark navy shorts, seen mostly from behind, with both arms raised gripping the top of the tailgate as if helping to load or unload. Some dark-red objects (possibly stacked chairs or equipment) sit on the truck bed behind the railings. The background is filled with dense dark-green foliage, a thick rough-barked tree trunk on the left, a small green shrub in the bottom-left corner, and a patch of blue sky in the top right. No boxes are actually visible in the photo — the item being handled is a bag.',

  // A scenic mountain lake at sunrise
  '1603979649806-5299879db16b':
    'A panoramic alpine landscape at sunrise or dusk. A calm mountain lake sits in a basin of rolling green grassy slopes dotted with rocks, its mirror-still surface reflecting the pink and lavender clouds above; a small grassy peninsula juts into the water at the lower middle. A narrow dirt footpath winds along the left shoreline and up the green hillside, and a dark rocky ridge rises at the far left. Behind the lake, layered blue-grey mountain ridges lead back to high, jagged peaks streaked with snow — a prominent pyramid-shaped peak stands slightly right of center, with another sharp summit to its left and more snow-capped peaks on the far right. The sky is pale blue with wispy pink-magenta clouds catching the light, and a warm golden-orange glow sits low on the left horizon. The dominant colors are green grass, slate-blue rock, white snow, pink clouds and silvery-lavender water. There are no people, animals, boats or buildings anywhere in the scene.',

  // Passengers waiting at a train station
  '1733315384471-0b84f65775c2':
    'A covered, elevated urban train station platform bathed in warm afternoon light. On the right, a white commuter metro train with a black window band and red accents (a red "rapid KL" logo and the car number 4311 on its front, headlights on, and a red LED destination sign above the windscreen) has stopped at the near track; a second empty track with brown rails and concrete sleepers runs beside it, separated from the far side by a long row of tall silver-grey metal mesh fence panels. The platform roof is a dark blue-grey arched steel truss structure supported by round dark-blue pillars, with fluorescent lights hanging beneath it. On the left platform, a small group of passengers waits: a man in a black T-shirt looking at his phone, a man in a white shirt, and several others; in the near foreground two blurred people stand close to the camera, one with black hair wearing a white face mask. A dark-green overhead sign reads "Platform 2A" with destinations "Putra Heights / Ampang", and an LED information board displays orange dot-matrix text. A yellow tactile safety strip runs along the platform edge. In the background stand white and cream buildings and an enclosed white-framed pedestrian bridge under a light-grey sky.',

  // A woman presenting a graph in a boardroom
  '1758691736545-5c33b6255dca':
    'A bright, minimalist white meeting room. The left wall is floor-to-ceiling glass with slim silver frames, through which a blurred white office space and a round skylight structure with metal framework are visible; two small black circular dots are mounted on the glass. In the center-left, a presenter — an East Asian woman with dark hair pulled into a neat high bun and round thin-framed glasses, wearing a fitted pale grey-blue turtleneck and a high-waisted grey knee-length pencil skirt — stands upright beside a large screen, holding a black pen in her right hand and facing her audience. The wall-mounted display has a black frame and black floor stand and shows a white slide titled "SALES VALUE": the left two-thirds is a large multi-line chart with jagged grey lines, and the right column holds two smaller bar charts with bars colored blue, teal and dark red. In the foreground, two colleagues watch with their backs to the camera: on the left, a woman with shoulder-length blonde hair in a white long-sleeved top sits at a white table on a black office chair with a pen and paper; on the right, closer to the camera, sits a balding man with short grey-brown hair, glasses and a beige shirt. The room is evenly lit, with a plain white wall and column on the right.',

  // Children playing in a park
  '1615489548573-8165c2c35e1b':
    'A sunny playground in a leafy green park. In the center, a laughing girl of about five or six, with light-brown hair in a ponytail, swings on a thick black knotted climbing rope that hangs from above. She wears a blue-and-green striped T-shirt, blue patterned denim shorts, colorful striped socks and black sneakers with yellow details, grips the rope with both hands and lifts her bent legs forward in mid-swing. Just behind and to the right, a younger child of about three or four, with shoulder-length light-brown hair, wearing a matching blue-and-green striped T-shirt, grey-lavender sweatpants and pink shoes, smiles broadly while reaching out one arm to push or hold the swinging girl. On the left stand two pale-yellow vertical metal poles connected by a dark horizontal ladder (monkey bars), and another yellow pole frames the right edge. The ground is packed light-brown dirt and sand marked with shadows from the trees. In the background, dense green woodland with white-barked birch trunks surrounds a dirt path, and on the far right a woman in a white top sits on an orange-brown wooden slatted bench, looking down at something in her hands.',

  // A chef preparing food in a restaurant
  '1668270973870-bb22ba5d1381':
    'A dim, moody professional restaurant kitchen seen from the dark dining room across a service counter. In the center, a chef with short dark hair, wearing a dark charcoal short-sleeved chef\'s shirt and a dark-brown apron tied at the waist, stands with his back to the camera, leaning over the stainless-steel pass as he arranges plates; a folded white kitchen towel lies on the counter beside his hands. A row of five or six polished copper dome-shaped heat lamps hangs above the pass on black coiled cords, glowing warmly. The kitchen behind him has white subway-tiled walls, a noticeboard with two rows of pinned white recipe sheets, flat-fronted stainless-steel wall cabinets, a red container on the counter to his right, a dark canister, and on the far right a tall dark combi-oven with a glowing illuminated control panel. The front of the counter is frosted white glass printed with an elegant dark script logo reading "Nokka" and the word "RAVINTOLA" in small capitals. In the shadowy foreground, dark wooden dining tables are set with groups of empty wine glasses, folded white napkins, cutlery and small dark plates, with black chair backs visible on the right. The palette is warm copper highlights against deep shadows.',

  // A crowded airport terminal
  '1674725690428-948af1d7f5a1':
    'A vast, modern airport terminal photographed from an elevated position. A huge white curved ceiling of long panel strips with skylight bands sweeps over the hall, supported by white steel trusses and thin diagonal cables; the right side is a tall glass curtain wall with a white lattice frame letting in daylight. The long concourse floor is tiled in a mottled orange-terracotta grid pattern with large darker rectangles, and dozens of small figures of travelers walk in both directions — several pulling wheeled suitcases or pushing silver luggage carts, a woman in a dark coat with a rolling bag in the lower right. Rows of silver luggage trolleys are parked in the middle of the floor beside free-standing black rectangular information kiosks. Along the left run two levels: a lower arcade of shops with dark storefronts and signs, and an upper mezzanine café with black railings where people sit at tables; an escalator and a staircase with blue edge markings descend at the bottom left, near a bright-yellow kiosk or vending machine. On the lower right, large dark flight-information screens showing white and green schedule text are mounted on a white wall, next to a hanging white sign with Japanese text (a security-check sign), gate letters "A B C" and yellow number codes. The hall recedes far into the distance toward more shops and signs.',

  // A couple shopping at a supermarket (actual photo shows two older adults)
  '1675179181865-0f1b17e070d6':
    'Two older adults stand talking in a grocery-store aisle. On the left, a person in their sixties with short dark-brown pixie-cut hair and rectangular dark-framed glasses wears a charcoal-black jacket over a pastel top with pink, green and cream horizontal stripes and a teal patterned scarf; they hold an empty metal wire shopping basket with a black handle in one hand at hip level and raise the other hand toward the product their companion is holding, looking at her with a slight smile. On the right, a woman in her sixties or seventies with short silver-grey hair, wearing a shiny bright-red quilted puffer jacket, holds up a rectangular brown-paper-packaged product (like a loaf of packaged bread or crispbread) and looks at her companion with her mouth open mid-sentence, as if discussing whether to buy it. Behind them on the left are white-framed glass-door refrigerated cases stocked with dairy-style products and shelf-edge price tags; on the right, tall shelves hold blue-and-white boxes and yellow packs on top, glass jars with red and yellow lids, cans, and brown packaged goods lower down, with white price labels along blue shelf rails. The store background is bright white and softly blurred.',

  // A team working on laptops around a wooden table
  '1522071820081-009f0129c71c':
    'Five young people work intensely on laptops around a dark wooden table in a warm, wood-panelled room with black-framed windows on the left. In the center foreground, a man seen from behind — short dark hair, large black over-ear headphones, dark grey T-shirt — types on a laptop whose dark screen is full of code. To his left, a woman with long dark hair rests her hand on the keyboard of a silver MacBook that also shows code. At the top of the table, a man in a mustard-tan hoodie with glasses and a beard leans his chin on his hand, thinking, in front of a silver laptop, with a clear plastic water bottle beside him. On the right, a man with curly blond hair, a faded grey graphic T-shirt, a white earbud in one ear and a black wristwatch sits sideways, turning to look toward his hoodie-wearing colleague. In the bottom-right corner, only the arms of a fifth person are visible typing on another laptop showing a bright webpage. In the middle of the table stand a small white vase of green-and-white flowers, a tall clear drinking glass, and a smartphone lying face-down. The chairs are simple wooden-slat chairs.',

  // A man presenting to colleagues in a meeting room
  '1542744173-8e7e53415bb0':
    'A bright office meeting room. On the left, a man with short dark hair, wearing a light-grey checked long-sleeve shirt and dark trousers, stands presenting next to a large wall-mounted TV that shows a slide with bold orange and white shapes. Behind him are a window with vertical white blinds, a dark sideboard holding an open silver MacBook, dark shelves with framed pictures and books, and a tall potted plant by a wooden door. Around a large oval light-wood table on black leather office chairs sit his colleagues: in the left foreground, a man with very short blond hair in a dark polo shirt seen from behind; beside him a woman with long dark hair in a dark top; across the table, a young man in a light-blue button-up shirt watching the presenter; and on the right, a woman with long auburn-brown hair in a sleeveless coral-red top. The table is crowded with open laptops (a Dell in the front, several MacBooks), five or six black-and-white striped gift bags stuffed with bright orange tissue paper, teal folders, notebooks, papers, phones and a water bottle. Part of another person in denim is visible in the bottom-right corner.',

  // Construction workers on a building site
  '1504307651254-35680f356dfd':
    'A construction site viewed from above, on a pale grey concrete deck. Two workers in high-visibility orange vests are at work. The upper worker, in an orange hard hat and an orange vest over grey sleeves with a white cloth at his neck, crouches while handling equipment near a long red-orange steel beam. The lower worker stands wearing an orange vest over a dark navy shirt, blue jeans, dark boots and a teal head covering over his face and neck, holding a tool at a metal sheet. Around them lies typical site material: a large coil of blue plastic tubing and a coil of green-and-blue cable on the left, rows of vertical steel rebar rising from red-edged formwork along the left edge, thick bundles of brown rebar rods stacked diagonally in the bottom-right and upper-right corners, a yellow cut-off saw machine in the center-right, a small grey generator or compressor beside it, a dark rectangular toolbox in the upper-left, scattered metal rods, wires, a green lifting strap, and red steel beams crossing the deck.',

  // A speaker giving a seminar to an audience
  '1524178232363-1fb2b075b655':
    'A seminar room with grey-green walls, an ornate cream patterned ceiling with recessed lights, and a black projector mounted near the top-right corner. At the back center, a presenter in a checked shirt stands at a dark podium with a silver laptop, speaking; behind him are two tall arched windows with white shutters and a potted plant between them. On the left, two large projection screens display the same white webpage-style slide. The audience — roughly a dozen adults — sits on black chairs with small attached side tables, mostly seen from behind: in the foreground a blonde woman in a salmon-pink shirt holds papers and a bottle of water, next to a man in a dark jacket; in the right-hand rows sit a man in a dark baseball cap and glasses looking down at his phone, a woman in a red top, a man in a purple shirt and another blonde woman. A camera tripod stands at the right edge of the frame, and the floor is dark polished concrete.',

  // A customer paying at a checkout counter
  '1556740738-b6a63e27c4df':
    'A bright, loft-style shop or salon interior with wooden ceiling beams, hanging pendant lights and a ceiling fan. At the center, a smiling young woman with long light-brown hair, wearing a rust-terracotta ribbed turtleneck sweater and a thin necklace, looks down as she taps or inserts her bank card into a black card-payment terminal on a grey counter. In the left foreground, only the outstretched arm and hand of the shop employee are visible, holding up a large black tablet screen (point-of-sale display) that shows a grid of product pictures. On the counter near her stand a small gold horse figurine and a phone in a holder; to the right are a black office chair and a glass desk with a black handbag and a pink tissue box. In the blurred background are salon-style stations with round illuminated mirrors, a few seated people, clothing racks, wooden pillars, white brick walls and a warmly lit doorway.',

  // A spacious café with customers and staff
  '1555396273-367ea4eb4db5':
    'A large, airy industrial-style café with high ceilings, exposed black steel beams and ducts, rows of black dome pendant lamps and strings of small bulbs. Along the left runs a long bar faced with stacked wooden slats: on it sit espresso machines, a pastry display and a register, with large black chalkboard menus hand-written in white hanging above; a barista in a dark shirt stands behind the bar and another staff member in white walks behind the counter. A woman with dark hair in a bun and a white top sits at a wooden table near the bar with a red bag beside her. The center of the room is filled with rows of light wooden tables and mismatched wooden chairs, mostly empty, each with a small menu stand. A white concrete staircase without railings climbs the white brick back wall, where a shelf display spells the word "love" among plants. On the right, tall glass doors with wooden frames let in daylight and show greenery outside; near them a man in a black T-shirt and shorts sits at a long wooden table working on a silver laptop, a black backpack at his feet. The floor is polished concrete.',

  // A man working on a laptop in a coffee shop
  '1554118811-1e0d58224f24':
    'A cozy, plant-filled café. The back wall is a huge black chalkboard covered in white handwritten menu items (Dutch words like "koffie" and "thee", and the name "BROEI"), above a bar with an espresso machine, rows of bottles on shelves, glasses and warm hanging Edison bulbs; a barista works behind the counter. A very large potted fiddle-leaf fig tree dominates the center of the room. In the foreground, white wire-frame chairs with wooden seats and mustard-yellow cushions surround a small round black table on a round dark rug; a low counter on the left holds drinking glasses, terracotta pots and small plants next to a small white sink basin, with an orange machine at the far left. On the right, a man wearing a dark jacket and a dark cap sits at a white table on a wooden chair, typing on a silver laptop, with a black bag on the bench beside him. The ceiling is industrial — white-painted beams, pipes, spotlights and a large black dome lamp — and the floor is concrete.',

  // A fruit and vegetable stall at a market
  '1488459716781-31db52582fe9':
    'An overflowing market produce stall with no people visible, photographed straight on. A silver weighing-scale pan hangs from chains at the top center. The back rows hold cantaloupe melons with yellow price stickers, upright bunches of pale green celery, large orange pumpkins and dark green squashes. The middle rows are packed with red and yellow bell peppers, romanesco and broccoli heads, purple artichokes, bundles of asparagus, orange carrots, vine tomatoes, beets, dark purple eggplants and clusters of cherry tomatoes. The front rows display exotic fruits, each with a small white handwritten price label: cut pink dragon fruit, green scaly custard apples, dark purple mangosteens, guavas halved to show pink flesh, brown snake fruit, red hairy rambutans, kumquats, lychees and clear plastic bags of leafy greens. The overall impression is a dense, extremely colorful wall of fresh produce in reds, greens, oranges, purples and yellows.',

  // Inside a clothing store
  '1441986300917-64674bd600d8':
    'The interior of a stylish menswear boutique with white walls and a bold blue-and-white triangle mural behind the central shelving. A black metal shelf unit with wooden boards holds black leather bags, a red-and-black backpack, folded navy jeans, black boots, a vintage camera, small framed pictures and shoe boxes; above it hang a worn vintage banner reading "BAGGAGE" and a large red letter "M", and a row of four white dome pendant lamps lights the room. On the left, a metal rail carries hanging shirts in grey, white, pink and checks with jackets below; on the right, another rail holds red, salmon-pink and navy coats and jackets. In the center stands a long wooden display table on a black frame stacked with folded navy and blue T-shirts, leather accessories and, on its lower shelf, brown boots, dark shoes, white boxes on concrete blocks and a folded grey blanket printed "U.S. NAVY". A framed photograph of a man leans against the wall on the right, and the floor is bare polished concrete.',

  // Students studying together in a library
  '1523240795612-9a054b0db644':
    'A bright study room or library. The entire back wall is white floor-to-ceiling shelving tightly packed with books, archive binders and journals in green, blue and dark spines, with rows of magazines on the lower shelves; a white-framed window on the left lets in daylight. Around a table, a group of young people bursts out laughing while looking at a silver laptop: in the center, a man with dark hair and a beard, wearing a grey henley shirt, leans over the laptop pointing at the screen and laughing; to his left, a man in a backwards white baseball cap, olive-green jacket and glasses laughs with his arms folded on the table; beside him, another man in a dark cap with a small red logo and glasses laughs broadly; at the right edge, a woman with long brown hair in a plaid shirt stands partly out of frame. On the table in the foreground are a pink folder, a white cup and the back of another laptop.',

  // A woman exercising on a mat
  '1571019613454-1cb2f99b2d8b':
    'A bright, minimal fitness space with a polished light-wood floor and a wall of huge windows so full of daylight they appear almost white, with trees faintly visible outside. A young woman lies on a black exercise mat doing sit-ups (crunches), photographed from floor level, side-on. Her dark hair is in a long braid that falls over her shoulder, and she wears red-tinted glasses, a white tank top, bright orange leggings and grey-white athletic sneakers with orange accents, plus a black smartwatch on her left wrist. Her knees are bent with feet flat on the mat, her hands are behind her head with elbows forward, and she is curling her upper body up mid-repetition. Her figure reflects softly in the shiny floor; in the far background outside the window, a blurred passer-by with a white bag can just be seen.',

  // The weight room in a gym
  '1534438327276-14e5300c3a48':
    'A gym weight room. The left half of the frame is filled by a long, two-tier rack of black rubber-coated dumbbells with silver handles, shot close-up so the nearest weights are large and the rack recedes diagonally into the distance; red-and-black weight labels are visible on the plates. To the right, on grey rubber flooring, a blonde woman in a black tank top, dark leggings with grey side panels and blue sneakers bends forward performing a dumbbell row near a black bench. Behind her stand squat racks with barbells, cable machines and mirrors; another person in dark clothing works out by the cardio machines at the far right, in front of tall windows with white blinds letting in bright daylight. Fluorescent strip lights run along the ceiling.',

  // Vegetable shelves in a supermarket
  '1542838132-92c53300491e':
    'A supermarket produce display with no people: four tiers of black shelving crates under a warm strip light. The top row holds heads of green leaf lettuce, bagged spinach, red bell peppers, piles of green cucumbers and courgettes, and yellow squash. The second row has red-purple radicchio and lettuce, mixed red and orange bell peppers, dark eggplants with cucumbers, orange-yellow peppers and bunches of celery and parsley. The third row shows red-leaf lettuce, fresh herbs like dill and parsley, trays of green, red and yellow peppers, more cucumbers and dark avocados. At floor level sit pale green cabbages, broccoli crowns in a crate, white net bags of garlic, a heap of cucumbers, packaged yellow snacks in plastic bags, and cauliflower heads. Small white price tags line every shelf edge, and the palette is dominated by fresh greens, reds and yellows.',

  // A hiker looking at a mountain lake
  '1503220317375-aaad61436b1b':
    'An overcast alpine scene. In the center foreground, a man is seen from behind, standing still and gazing out over a calm mountain lake. He wears a dark navy baseball cap with white embroidered lettering, a white T-shirt with thin navy horizontal stripes, and carries a large coral-pink backpack with black straps, buckles and cords; a camera hangs at his side. The lake\'s surface is smooth slate-grey-green, softly reflecting the sky. Beyond the water, steep forested slopes in deep green rise on both sides, layered in front of grey rocky mountain ridges that recede toward a misty, cloud-filled valley at the far end. The sky is heavy with white-grey clouds, with one soft bright patch of light in the middle. A dark green shrub occupies the bottom-left corner. The palette is muted — greys and deep greens — with the coral backpack as the single strong color accent.',

  // A wooden boat on a mountain lake
  '1476514525535-07fb3b4ae5f1':
    'A first-person view from the bow of a classic varnished wooden rowing boat pointing out across a milky turquoise alpine lake. The glossy honey-brown wooden deck and plank sides of the boat fill the bottom of the frame in a V-shape, with a small metal mooring post at the tip of the bow. The rippled emerald-turquoise water stretches ahead to a shoreline of dense, dark green conifer forest. Behind the trees rises a massive pale-grey rocky mountain wall with sheer cliffs, scree channels and ledges dotted with pines — brightest on the right, with more rugged grey crags on the left. The sky is flat, overcast white. Tiny boats and a dock are just visible as small dots along the far left shore. No people are visible.',

  // An airplane wing above the clouds
  '1436491865332-7a61a109cc05':
    'A view from an airplane window high above the clouds at sunrise or sunset. The aircraft\'s silver-grey wing stretches from the lower-left across to the right of the frame, tipped with an upswept dark winglet; two grey flap-track fairing pods are visible under its trailing edge. Below and beyond the wing lies an endless field of soft white and golden cumulus clouds glowing in warm light. In the upper-left, the sky is cool blue-grey with a towering bank of cumulus cloud; on the right, the low sun creates a bright glare just above the cloud horizon, washing that side in pale peach, gold and pink haze. A faint contrail line crosses the sky on the left. There are no people or land visible — only wing, sky and clouds in a soft pastel palette.',

  // A tropical beach with palm trees
  '1672841828459-bc913fdcd995':
    'A pristine tropical beach under a vivid cyan-blue sky that is nearly cloudless, with only faint wispy white clouds low near the horizon. The sea forms bands of color: pale, glassy aqua shallows over white sand near the shore, turquoise in the middle, and deeper teal-blue toward the horizon, where a thin dark strip of a distant island or long jetty with tiny white dots is faintly visible. The water is extremely calm, with only small ripples lapping the shore. The beach is bright white-cream fine sand, smooth with gentle undulations, footprint marks and scattered palm-frond shadows. The most striking feature is a long, slender grey-brown palm trunk that leans from the left and arcs down low, almost horizontally, over the sand toward the sea, its crown of green fronds hanging in the center of the frame. Behind it, a cluster of three or four more upright coconut palms with starburst crowns rises from dense green tropical vegetation that covers the left side; dry brown fallen fronds lie at the vegetation line, and a leafy branch overhangs the top-left corner. The light is bright midday sun with high contrast and saturated colors. No people, boats or animals are visible.',
};

// Match the photo id in both forms the app uses: the bundled local copy
// (/images/practice/photo-<id>.jpg) and any size/crop variant of the original
// Unsplash URL (kept for practices saved before the images went local).
const PHOTO_ID_RE = /photo-([a-zA-Z0-9]+-[a-zA-Z0-9]+)/;

/**
 * Return the baked, human-verified description for a known practice photo, or
 * undefined for AI-generated / placeholder images we have never looked at.
 */
export const getBakedImageDescription = (imageUrl: string): string | undefined => {
  const id = imageUrl.match(PHOTO_ID_RE)?.[1];
  return id ? UNSPLASH_PHOTO_DESCRIPTIONS[id] : undefined;
};
